#!/usr/bin/env python3
"""Build the enclosure: run the fit checks, export print files and PCB inputs, render previews.

    ~/.venvs/cad/bin/python hardware/enclosure/build.py [--no-render]

Outputs go to hardware/enclosure/out/ (git-ignored; regenerate rather than commit). Exits
non-zero if any fit check fails.
"""

import json
import sys
from pathlib import Path

from build123d import Align, Axis, Box, Color, Compound, ExportDXF, Mesher, Pos, export_step, export_stl

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import checks  # noqa: E402
import model as m  # noqa: E402
import params  # noqa: E402

OUT = HERE / "out"


FITCHECK_ABOVE_PANEL = 12.0   # mm of the display window included above the panel's bottom edge


def fitcheck(printed):
    """Cheap first print: the bottom of the front shell (chin + the panel's bottom edge) and the
    knob. Tests the knob/bushing, USB-C, microSD and button openings, the chin bosses/inserts and
    the panel's bottom locating rib against the real parts before the full set is ordered."""
    y_cut = m.PANEL_BOT + FITCHECK_ABOVE_PANEL
    keep = Pos(0, y_cut, -1) * Box(500, 500, 100, align=(Align.CENTER, Align.MAX, Align.MIN))
    return {"fitcheck_chin": printed["front_shell"] & keep, "fitcheck_knob": printed["knob"]}


def write_part(name, part):
    export_step(part, OUT / f"{name}.step")
    export_stl(part, OUT / f"{name}.stl", tolerance=0.02, angular_tolerance=0.1)
    mesher = Mesher()
    mesher.add_shape(part, linear_deflection=0.02, angular_deflection=0.1)
    mesher.write(str(OUT / f"{name}.3mf"))


def export(printed, components):
    OUT.mkdir(exist_ok=True)
    fc = fitcheck(printed)
    for name, part in {**printed, **fc}.items():
        write_part(name, part)
    for name, part in fc.items():
        bb = part.bounding_box()
        print(f"  fit-check {name}: {bb.size.X:.1f} x {bb.size.Y:.1f} x {bb.size.Z:.1f} mm, "
              f"{part.volume / 1000:.1f} cm^3, ~{part.volume * m.PA12_DENSITY:.1f} g PA12")

    children = []
    from render import COLORS
    for name, part in {**printed, **components}.items():
        if name in ("usb_plug", "sd_card_path"):
            continue
        part.label = name
        part.color = Color(COLORS[name][0])
        children.append(part)
    export_step(Compound(children=children, label="epaper_enclosure_assembly"), OUT / "assembly.step")

    # PCB outline for KiCad: File > Import > Graphics, layer Edge.Cuts, scale 1, mm.
    face = m.pcb().faces().sort_by(Axis.Z)[0]
    dxf = ExportDXF()
    dxf.add_shape(Pos(0, 0, -m.Z_PCB) * face)
    dxf.write(OUT / "pcb_outline.dxf")


def placement():
    """Where the enclosure needs things on the PCB. Device frame: origin = device centre (see
    params.py). PCB frame: origin = PCB lower-left corner as seen from the component (front) side."""
    def pcb_xy(x, y):
        return [round(x - m.PCB_X0, 3), round(y - m.PCB_Y0, 3)]

    return {
        "note": "Generated by hardware/enclosure/build.py - edit params.py, not this file.",
        "pcb_size_mm": [round(m.PCB_X1 - m.PCB_X0, 3), round(m.PCB_Y1 - m.PCB_Y0, 3)],
        "pcb_thickness_mm": params.PCB_T,
        "max_top_side_part_height_under_backer_mm": round(params.Z_BACKER - params.Z_PCB_TOP
                                                          - params.FIT_CLEAR, 2),
        "max_top_side_part_height_in_chin_mm": round(params.Z_BEZEL - params.Z_PCB_TOP - params.FIT_CLEAR, 2),
        "max_bottom_side_part_height_mm": round(params.PCB_STANDOFF - 0.3, 2),
        "mounting_holes_pcb_xy": [pcb_xy(x, y) for x, y in m.PCB_HOLES],
        "mounting_hole_d_mm": m.PCB_HOLE_D,
        "boss_notches_pcb_xy": [pcb_xy(x, y) for x, y, _ in m.BOSSES if y < m.PCB_Y1],
        "boss_notch_d_mm": m.PCB_NOTCH_D,
        "encoder_axis_pcb_xy": pcb_xy(m.ENC_X, m.ENC_Y),
        "usb_c_centre_on_bottom_edge_pcb_x": round(params.USB_X - m.PCB_X0, 3),
        "usb_c_mouth": "flush with the PCB bottom edge",
        "microsd_card_centre_on_bottom_edge_pcb_x": round(params.SD_X - m.PCB_X0, 3),
        "battery_lead_edge_above_pcb_top_mm": round(m.BATT_Y0 - m.PCB_Y1, 2),
        "battery_zone_x_pcb": [round(m.BATT_X0 - m.PCB_X0, 2),
                               round(m.BATT_X0 + m.BATT_ZONE_W - m.PCB_X0, 2)],
        "electrode_zones_y_device": [[yc - params.ELECTRODE_H / 2, yc + params.ELECTRODE_H / 2]
                                     for yc in params.ELECTRODE_Y],
        "electrode_zones_y_pcb": [[round(yc - params.ELECTRODE_H / 2 - m.PCB_Y0, 2),
                                   round(yc + params.ELECTRODE_H / 2 - m.PCB_Y0, 2)]
                                  for yc in params.ELECTRODE_Y],
        "hat_outline_device": [[m.HAT_X - params.HAT_W / 2, m.HAT_Y0], [m.HAT_X + params.HAT_W / 2, m.HAT_Y1]],
        "power_switch_SW302": {
            "part": "Alps SKRTLAE010, plunger facing the bottom edge",
            "centre_x_pcb": round(params.BTN_X - m.PCB_X0, 3),
            "plunger_tip": "flush with the PCB bottom edge",
        },
        "electrode_connectors_J302_J303": "top corners of the PCB, cable to the electrode board "
                                          "connectors at device y = %.1f" % params.EB_CONN_Y,
        "rt1_ntc": "leaded NTC solder pads near the PCB's top-left edge: the battery's lead edge "
                   "is %.1f mm above, at x_pcb %.1f..%.1f" % (
                       m.BATT_Y0 - m.PCB_Y1, m.BATT_X0 - m.PCB_X0, m.BATT_X0 + m.BATT_ZONE_W - m.PCB_X0),
    }


def electrode_board():
    """The electrode board (one design, fitted on both sides). Board frame, looking at the PAD
    side: u along the board (device Y, from its bottom end), v across it (device Z, from its back
    edge). The connector goes on the other side, centred across the board so the same board fits
    left and right (the right one is the left one turned over)."""
    L, W = m.EB_Y1 - m.EB_Y0, params.EB_W
    pads = []
    for yc in params.ELECTRODE_Y:
        u0 = yc - params.ELECTRODE_H / 2 - m.EB_Y0
        pads.append([round(u0, 2), 1.0, round(u0 + params.ELECTRODE_H, 2), round(W - 1.0, 2)])
    return {
        "note": "Generated by hardware/enclosure/build.py - edit params.py, not this file.",
        "board_mm": [round(L, 2), W], "thickness_mm": params.EB_T,
        "pads_u0_v0_u1_v1": pads,
        "pads_side": "facing the enclosure wall; keep GND copper off this side",
        "connector": {"part": "JST SM03B-SRSS-TB (horizontal)", "side": "back (away from the wall)",
                      "centre_uv": [round(params.EB_CONN_Y - m.EB_Y0, 2), W / 2],
                      "pinout": "1 touch (lower zone), 2 GND, 3 touch (upper zone)"},
        "retention": "slides into printed channels at both ends; keep 1.5 mm at each end free of "
                     "parts and copper",
    }


def main():
    render = "--no-render" not in sys.argv
    printed, components = m.build()

    print(f"Outer size: {params.OUTER_W:.1f} x {params.OUTER_H:.1f} x {params.OUTER_T:.2f} mm "
          f"(W x H x T), knob adds {m.Z_KNOB_TOP - params.OUTER_T:.1f} mm")
    driver, zones = checks.thickness_driver()
    print(f"Cavity depth {params.CAVITY_T:.2f} mm, set by {driver}: "
          + ", ".join(f"{k} {v:.1f}" for k, v in zones.items()))
    total = 0.0
    for name, part in printed.items():
        grams = part.volume * m.PA12_DENSITY
        total += grams
        bb = part.bounding_box()
        print(f"  {name:14s} {bb.size.X:6.1f} x {bb.size.Y:6.1f} x {bb.size.Z:5.1f} mm  "
              f"{part.volume / 1000:6.1f} cm^3  ~{grams:5.1f} g PA12")
    print(f"  {'total':14s} ~{total:.0f} g printed")

    results = checks.rules() + checks.interferences(printed, components)
    print("\nChecks:")
    for ok, msg in results:
        print(f"  [{'ok' if ok else 'FAIL'}] {msg}")

    print("\nPlaceholders to measure/verify before ordering (params.py, tag PH):")
    for name, value, src, note in params.REGISTRY:
        if src == "PH":
            print(f"  {name} = {value}: {note}")

    export(printed, components)
    (OUT / "pcb_placement.json").write_text(json.dumps(placement(), indent=2) + "\n")
    (OUT / "electrode_board.json").write_text(json.dumps(electrode_board(), indent=2) + "\n")
    print(f"\nExported to {OUT.relative_to(HERE.parent.parent)}/")
    if render:
        from render import render_all
        for p in render_all(printed, components, OUT):
            print(f"  rendered {p.name}")

    return 0 if all(ok for ok, _ in results) else 1


if __name__ == "__main__":
    sys.exit(main())
