#ifndef EPD_FONTAA_H
#define EPD_FONTAA_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Anti-aliased bitmap font format, generated by tools/gen_font.py from a
   real TTF/OTF at a fixed pixel size (see that script for how). Each glyph
   is proportionally-widthed (its own advance width) and stores 4-bit AA
   coverage per pixel (0=no ink, 15=full ink), packed 2px/byte with the same
   nibble order used elsewhere in this project (low nibble = even x column,
   high nibble = odd x column). Height is fixed per font (ascent+descent).

   This is a different, richer format than the plain sFONT bitmap fonts in
   this same directory (Drivers/Fonts/font{8,12,16,20,24}.c) - those are
   fixed-width, 1-bit-per-pixel, no anti-aliasing. Use EPD_Text_DrawStringAA
   (EPD_Text.h) to draw fonts in this format. */
typedef struct
{
  uint8_t width;         /* glyph advance width in pixels */
  const uint8_t *bitmap; /* height rows x ceil(width/2) bytes/row, 4bpp packed */
} EPD_GlyphAA;

typedef struct
{
  const EPD_GlyphAA *glyphs;
  uint8_t firstChar;
  uint8_t lastChar;
  uint8_t height; /* fixed line height in pixels, same for every glyph */
} EPD_FontAA;

/* Generated fonts (tools/gen_font.py). All from Liberation Serif (SIL Open
   Font License 1.1) - see README for attribution. */
extern const EPD_FontAA Font32;      /* Regular, 32px, 36px line height */
extern const EPD_FontAA Font44;      /* Regular, 44px, 50px line height */
extern const EPD_FontAA Font60Bold;  /* Bold, 60px, 67px line height */

#ifdef __cplusplus
}
#endif

#endif /* EPD_FONTAA_H */
