"""Power sheet: USB-C input, LFP charger, load sharing, 3V3/5V converters, RTC backup, reserved
low-power islands. See README "Power Sheet (drafted in KiCad)" for the design decisions."""
from common import C0402, C0603, C0805, R0402, flag, new_sheet, two_pin

# Signals that leave this sheet for the (future) MCU sheet.
GLOBAL = {'USB_DP': 'bidirectional', 'USB_DM': 'bidirectional', 'CHG_STAT': 'output',
          '3V3_PG': 'output', 'EPD_5V_EN': 'input', 'VBAT_RTC': 'output', 'PERIPH_EN': 'input'}


def build():
    s = new_sheet('Power', GLOBAL)
    s.text('POWER — draft (generated by hardware/scripts/gen_schematic.py; edit in Eeschema '
           'from here on)\nSee README.md "Custom PCB (Planned)" and TODO.md for the open '
           'questions on this sheet.', 20.32, 12.7, size=2)

    # ---- USB-C (sink) + ESD ------------------------------------------------------------
    s.text('USB-C receptacle, UFP/sink only: 5.1k Rd on each CC.\nD+/D- to MCU USB OTG_FS '
           '(PA11/PA12) for DFU/CDC.\nSHIELD tied straight to GND for now (revisit: RC/ferrite).',
           20.32, 30.48)
    j1 = s.part('J1', 'Connector:USB_C_Receptacle_USB2.0_16P', 'USB_C_Receptacle_USB2.0_16P',
                40.64, 76.2,
                footprint='Connector_USB:USB_C_Receptacle_GCT_USB4105-xx-A_16P_TopMnt_Horizontal',
                fields={'MPN': 'GCT USB4105-GF-A'})
    s.conns(j1, {'A4': 'VBUS', 'A5': 'CC1', 'B5': 'CC2', 'A6': 'USB_DP', 'B6': 'USB_DP',
                 'A7': 'USB_DM', 'B7': 'USB_DM', 'A8': None, 'B8': None, 'A1': 'GND',
                 'SH': 'GND'})
    two_pin(s, 'R1', 'R', '5.1k', 71.12, 104.14, 'CC1', 'GND', R0402)
    two_pin(s, 'R2', 'R', '5.1k', 81.28, 104.14, 'CC2', 'GND', R0402)

    u5 = s.part('U5', 'Power_Protection:USBLC6-2SC6', 'USBLC6-2SC6', 101.6, 76.2)
    s.conns(u5, {'1': 'USB_DP', '6': 'USB_DP', '3': 'USB_DM', '4': 'USB_DM', '5': 'VBUS',
                 '2': 'GND'})
    flag(s, 'VBUS', 91.44, 50.8)
    flag(s, 'GND', 114.3, 50.8)

    # ---- LiFePO4 charger ---------------------------------------------------------------
    s.text('MCP73123-22S/MF: LiFePO4 linear charger, 3.6V CV (NOT MCP73831 — 4.2V kills LFP).\n'
           'R_PROG 2.37k -> I_REG = 1104*R^-0.93 = ~495mA (DS22191E Eq. 5-1). Pick to suit cell.\n'
           'Dissipation ~ (5V-3.2V)*0.5A = 0.9W: needs thermal vias under EP.\n'
           'STAT: LED from VBUS (works with MCU off) + CHG_STAT to an FT (5V-tolerant) GPIO.',
           137.16, 30.48)
    u1 = s.part('U1', 'epaper:MCP73123', 'MCP73123-22S/MF', 177.8, 76.2,
                fields={'MPN': 'MCP73123-22SI/MF'})
    s.conns(u1, {'1': 'VBUS', '10': 'PROG', '5': None, '6': None, '3': '+BATT',
                 '7': 'CHG_STAT', '8': 'GND', '11': 'GND'})
    two_pin(s, 'C1', 'C', '4.7uF', 142.24, 104.14, 'VBUS', 'GND', C0603)
    two_pin(s, 'R3', 'R', '2.37k 1%', 152.4, 104.14, 'PROG', 'GND', R0402)
    two_pin(s, 'C2', 'C', '4.7uF', 203.2, 104.14, '+BATT', 'GND', C0603)
    two_pin(s, 'R4', 'R', '1k', 213.36, 104.14, 'VBUS', 'CHG_LED', R0402)
    d2 = s.part('D2', 'Device:LED', 'CHG (red)', 231.14, 88.9,
                footprint='LED_SMD:LED_0603_1608Metric')
    s.conns(d2, {'2': 'CHG_LED', '1': 'CHG_STAT'})

    # ---- RTC backup ---------------------------------------------------------------------
    s.text('RTC backup: cell -> Schottky -> STM32 VBAT.\nFull LFP 3.65V - ~0.3V drop keeps '
           'VBAT under its 3.6V max.', 266.7, 30.48)
    d3 = s.part('D3', 'Device:D_Schottky', 'BAT54J', 287.02, 60.96,
                footprint='Diode_SMD:D_SOD-323F', fields={'MPN': 'BAT54J,115'})
    s.conns(d3, {'2': '+BATT', '1': 'VBAT_RTC'})
    two_pin(s, 'C3', 'C', '100nF', 309.88, 68.58, 'VBAT_RTC', 'GND', C0402)

    # ---- Battery + load sharing ---------------------------------------------------------
    s.text('Battery: JST-PH 2-pin (pin 1 = +). CHECK cell lead polarity — not standardised.\n'
           'Load sharing (Microchip AN1149): with USB present, D1 feeds VSYS from VBUS and\n'
           'Q1 is off, so the charger sees only the cell and terminates correctly.\n'
           'On battery, R5 pulls Q1 gate low -> Q1 on, cell feeds VSYS. R5 = 10k (not 100k)\n'
           'so D1 reverse leakage (tens of uA hot) cannot lift the gate and half-close Q1.',
           20.32, 129.54)
    j2 = s.part('J2', 'Connector_Generic:Conn_01x02', 'BATT (LiFePO4)', 50.8, 170.18,
                footprint='Connector_JST:JST_PH_S2B-PH-SM4-TB_1x02-1MP_P2.00mm_Horizontal')
    s.conns(j2, {'1': '+BATT', '2': 'GND'})

    d1 = s.part('D1', 'Device:D_Schottky', 'PMEG2010AEH', 81.28, 154.94,
                footprint='Diode_SMD:D_SOD-123F', fields={'MPN': 'PMEG2010AEH,115'})
    s.conns(d1, {'2': 'VBUS', '1': 'VSYS'})
    q1 = s.part('Q1', 'Transistor_FET:AO3401A', 'AO3401A', 86.36, 175.26)
    s.conns(q1, {'1': 'VBUS', '2': 'VSYS', '3': '+BATT'})
    two_pin(s, 'R5', 'R', '10k', 71.12, 195.58, 'VBUS', 'GND', R0402)
    flag(s, 'VSYS', 106.68, 154.94)

    # ---- 3.3V buck-boost + battery undervoltage cutoff -----------------------------------
    s.text('TPS63802 buck-boost -> +3V3 (VOUT = 0.5V*(1+R7/R8) = 3.308V, datasheet Fig. 10-1).\n'
           'MODE low = power-save (PFM). Starts from VIN > 1.8V, 11uA Iq.\n'
           'UNDERVOLTAGE CUTOFF: EN has a precise threshold (1.10V rising / 1.00V falling), so\n'
           'R6/R15 from VSYS turn the rail OFF below ~2.80V and back ON above ~3.08V (+-3%),\n'
           '~1.2uA. Hardware backstop only: firmware should shut down gracefully first\n'
           '(~3.0V, via the STM32 internal VBAT ADC channel on VBAT_RTC). The charger does NOT\n'
           'protect against over-discharge. Footprint: project lib (TI DLA0010A land pattern).',
           137.16, 129.54)
    u2 = s.part('U2', 'epaper:TPS63802', 'TPS63802DLA', 177.8, 175.26,
                fields={'MPN': 'TPS63802DLAR'})
    s.conns(u2, {'10': 'VSYS', '1': 'BB_EN', '2': 'GND', '6': '+3V3', '4': 'BB_FB',
                 '5': '3V3_PG', '9': 'BB_L1', '7': 'BB_L2', '3': 'GND', '8': 'GND'})
    two_pin(s, 'C4', 'C', '10uF', 129.54, 210.82, 'VSYS', 'GND', C0603,
            fields={'Voltage': '10V'})
    two_pin(s, 'C5', 'C', '10uF', 139.70, 210.82, 'VSYS', 'GND', C0603,
            fields={'Voltage': '10V'})
    two_pin(s, 'R6', 'R', '1.8M 1%', 149.86, 210.82, 'VSYS', 'BB_EN', R0402)
    two_pin(s, 'R15', 'R', '1M 1%', 160.02, 210.82, 'BB_EN', 'GND', R0402)
    two_pin(s, 'L1', 'L', '0.47uH', 180.34, 210.82, 'BB_L1', 'BB_L2',
            'Inductor_SMD:L_Murata_DFE201610P',
            fields={'MPN': 'DFE201612E-R47M (TI Table 10-2: 5.5A Isat; verify land pattern)'})
    two_pin(s, 'R7', 'R', '511k 1%', 190.50, 210.82, '+3V3', 'BB_FB', R0402)
    two_pin(s, 'R8', 'R', '91k 1%', 200.66, 210.82, 'BB_FB', 'GND', R0402)
    two_pin(s, 'C8', 'C', '22uF', 210.82, 210.82, '+3V3', 'GND', C0603)
    two_pin(s, 'C9', 'C', '22uF', 220.98, 210.82, '+3V3', 'GND', C0603)
    two_pin(s, 'R9', 'R', '100k', 231.14, 210.82, '+3V3', '3V3_PG', R0402)

    # ---- 5V boost for the external Waveshare HAT (v1) ------------------------------------
    s.text('TPS61023 boost -> +5V for the EXTERNAL Waveshare IT8951 HAT (v1 board: HAT on an\n'
           'SPI connector - connector lives on the peripheral sheet). VOUT = 0.6V*(1+R10/R11)\n'
           '= 4.99V. True disconnect in shutdown; R12 holds it OFF until the MCU drives EPD_5V_EN.',
           274.32, 129.54)
    u3 = s.part('U3', 'epaper:TPS61023', 'TPS61023DRL', 304.8, 175.26,
                fields={'MPN': 'TPS61023DRLR'})
    s.conns(u3, {'3': 'VSYS', '2': 'EPD_5V_EN', '6': '+5V', '1': 'BST_FB', '5': 'BST_SW',
                 '4': 'GND'})
    two_pin(s, 'C11', 'C', '10uF', 274.32, 210.82, 'VSYS', 'GND', C0603)
    two_pin(s, 'L2', 'L', '1uH', 284.48, 210.82, 'VSYS', 'BST_SW',
            'Inductor_SMD:L_Murata_DFE201610P',
            fields={'MPN': 'DFE201610P-1R0M (verify Isat vs 3.7A valley limit)'})
    two_pin(s, 'R12', 'R', '1M', 294.64, 210.82, 'EPD_5V_EN', 'GND', R0402)
    two_pin(s, 'R10', 'R', '732k 1%', 304.80, 210.82, '+5V', 'BST_FB', R0402)
    two_pin(s, 'R11', 'R', '100k 1%', 314.96, 210.82, 'BST_FB', 'GND', R0402)
    two_pin(s, 'C12', 'C', '22uF', 325.12, 210.82, '+5V', 'GND', C0805)
    two_pin(s, 'C13', 'C', '22uF', 335.28, 210.82, '+5V', 'GND', C0805)

    # ---- Reserved: always-on nanopower rail (DNP on v1) ---------------------------------
    s.text('RESERVED (DNP) for low-power v2: TPS63900 always-on\n'
           '3V3_AON (75nA Iq) for MCU + CAP1188. Replaces MAX17222,\n'
           'which is boost-only and cannot regulate a 3.65V cell down.\n'
           'VO(1) = 3.3V via CFG3 = 16.2k (SEL low); CFG1/CFG2 = 0R\n'
           '-> no input current limit. v1: R18 0R feeds 3V3_AON from\n'
           '+3V3. v2 TODO: EN needs its own UVLO (logic-level EN).',
           342.9, 30.48)
    u6 = s.part('U6', 'epaper:TPS63900', 'TPS63900DSK', 370.84, 76.2, dnp=True,
                fields={'MPN': 'TPS63900DSKR'})
    s.conns(u6, {'10': 'VSYS', '1': 'AON_EN', '2': 'GND', '6': '3V3_AON', '3': 'GND',
                 '4': 'GND', '5': 'AON_CFG3', '9': 'AON_LX1', '7': 'AON_LX2', '8': 'GND',
                 '11': 'GND'})
    two_pin(s, 'C6', 'C', '10uF', 342.9, 104.14, 'VSYS', 'GND', C0603, dnp=True)
    two_pin(s, 'R17', 'R', '100k', 353.06, 104.14, 'VSYS', 'AON_EN', R0402, dnp=True)
    two_pin(s, 'L3', 'L', '2.2uH', 363.22, 104.14, 'AON_LX1', 'AON_LX2',
            'Inductor_SMD:L_Murata_DFE201610P', dnp=True,
            fields={'MPN': '2.2uH per TPS63900 datasheet; pick the part at v2'})
    two_pin(s, 'R16', 'R', '16.2k 1%', 373.38, 104.14, 'AON_CFG3', 'GND', R0402, dnp=True)
    two_pin(s, 'C7', 'C', '22uF', 383.54, 104.14, '3V3_AON', 'GND', C0603, dnp=True)
    two_pin(s, 'R18', 'R', '0R', 393.7, 104.14, '+3V3', '3V3_AON', R0402)

    # ---- Reserved: peripheral load switch (DNP on v1) -----------------------------------
    s.text('RESERVED for low-power v2 (README "Sleep current"): TPS22965 gating 3V3_PERIPH\n'
           '(SDRAM, microSD). v1: U4/R14/C14 DNP, R13 0R bypass fitted.',
           137.16, 236.22)
    u4 = s.part('U4', 'epaper:TPS22965', 'TPS22965DSG', 177.8, 264.16, dnp=True,
                fields={'MPN': 'TPS22965DSGR'})
    s.conns(u4, {'1': '+3V3', '4': '+3V3', '3': 'PERIPH_EN', '7': '3V3_PERIPH', '6': 'LS_CT',
                 '5': 'GND', '9': 'GND'})
    two_pin(s, 'R13', 'R', '0R', 205.74, 269.24, '+3V3', '3V3_PERIPH', R0402)
    two_pin(s, 'R14', 'R', '100k', 147.32, 276.86, 'PERIPH_EN', 'GND', R0402, dnp=True)
    two_pin(s, 'C14', 'C', '1nF', 215.9, 269.24, 'LS_CT', 'GND', C0402, dnp=True)
    return s
