"""Power sheet: USB-C input, LiPo charger with power path, 3V3/5V converters, RTC backup, reserved
low-power islands. See README "Power Sheet (drafted in KiCad)" for the design decisions."""
from common import C0402, C0603, C0805, R0402, R0603, flag, new_sheet, two_pin

# Signals that leave this sheet for the (future) MCU sheet.
GLOBAL = {'USB_DP': 'bidirectional', 'USB_DM': 'bidirectional', 'CHG_STAT': 'output',
          '3V3_PG': 'output', 'EPD_5V_EN': 'input', 'VBAT_RTC': 'output', 'PERIPH_EN': 'input',
          'VBAT_SENSE': 'output', 'CHG_DIS': 'input', 'TS_SENSE': 'output'}


def build():
    s = new_sheet('Power', GLOBAL)
    s.text('POWER — draft (generated by hardware/scripts/gen_schematic.py; edit in Eeschema '
           'from here on)\nSee README.md "Custom PCB (Planned)" and TODO.md for the open '
           'questions on this sheet.', 20.32, 12.7, size=2)

    # ---- USB-C (sink) + ESD ------------------------------------------------------------
    s.text('USB-C receptacle, UFP/sink only: 5.1k Rd on each CC.\nD+/D- to MCU USB OTG_FS '
           '(PA11/PA12) for DFU/CDC.\nSHIELD tied straight to GND for now (revisit: RC/ferrite).',
           20.32, 30.48)
    j1 = s.part('J1', 'Connector:USB_C_Receptacle_USB2.0_16P', 'USB_C_Receptacle_USB2.0_16P',
                40.64, 76.2,
                footprint='Connector_USB:USB_C_Receptacle_GCT_USB4105-xx-A_16P_TopMnt_Horizontal',
                fields={'MPN': 'GCT USB4105-GF-A'})
    s.conns(j1, {'A4': 'VBUS', 'A5': 'CC1', 'B5': 'CC2', 'A6': 'USB_DP', 'B6': 'USB_DP',
                 'A7': 'USB_DM', 'B7': 'USB_DM', 'A8': None, 'B8': None, 'A1': 'GND',
                 'SH': 'GND'})
    two_pin(s, 'R1', 'R', '5.1k', 71.12, 104.14, 'CC1', 'GND', R0402)
    two_pin(s, 'R2', 'R', '5.1k', 81.28, 104.14, 'CC2', 'GND', R0402)

    u5 = s.part('U5', 'Power_Protection:USBLC6-2SC6', 'USBLC6-2SC6', 101.6, 76.2)
    s.conns(u5, {'1': 'USB_DP', '6': 'USB_DP', '3': 'USB_DM', '4': 'USB_DM', '5': 'VBUS',
                 '2': 'GND'})
    flag(s, 'VBUS', 91.44, 50.8)
    flag(s, 'GND', 114.3, 50.8)

    # ---- LiPo charger with power path ---------------------------------------------------
    s.text('BQ24073 1-cell Li-ion/LiPo charger with power path (TI SLUS810N): 4.2V CV, OUT =\n'
           'VSYS regulated to 4.4V with USB present (keeps the 5.5V-max converters safe), battery\n'
           'supplement when the load exceeds the input limit, 6.6V input OVP.\n'
           'ISET 3.01k -> 890/3.01k = ~296mA (265-324mA worst case): <= 0.3C of the 1100mAh cell,\n'
           'which is EEMB\'s limit for charging at 0-20C (either candidate cell is in spec anywhere).\n'
           'EN2=0/EN1=1 -> USB500 input limit (USB-C default power, no CC advertisement read).\n'
           'ILIM 1.54k (1.0A) must be fitted anyway: an open ILIM disables charging.\n'
           'TS: on-board 10k NTC against the cell; charger blocks charging outside ~0-50C. The\n'
           'cells allow only 0-45C and no NTC can narrow the window (TI eq. 8 needs a cold/hot\n'
           'resistance ratio of 7), so firmware reads TS_SENSE and drives CHG_DIS (CE, 100k\n'
           'pull-down = charging on while the MCU is off) to suspend charging at 43-50C.\n'
           'TMR 72k: fast-charge timer 7.2-12h (default 4-6h would expire on the 1800mAh cell).\n'
           'TD low (termination on). CHG: LED from VBUS + CHG_STAT to an FT GPIO.',
           137.16, 30.48)
    u1 = s.part('U1', 'Battery_Management:BQ24073RGT', 'BQ24073RGT', 177.8, 83.82,
                fields={'MPN': 'BQ24073RGTR'})
    s.conns(u1, {'13': 'VBUS', '2': '+BATT', '10': 'VSYS', '16': 'ISET', '12': 'ILIM',
                 '1': 'TS', '9': 'CHG_STAT', '7': None, '5': 'GND', '6': 'CHG_EN1',
                 '4': 'CHG_DIS', '15': 'GND', '14': 'TMR', '8': 'GND', '17': 'GND'})
    two_pin(s, 'C1', 'C', '4.7uF', 142.24, 111.76, 'VBUS', 'GND', C0603,
            fields={'Voltage': '10V'})
    two_pin(s, 'R3', 'R', '3.01k 1%', 152.4, 111.76, 'ISET', 'GND', R0402)
    two_pin(s, 'R23', 'R', '72k 1%', 182.88, 111.76, 'TMR', 'GND', R0402)
    two_pin(s, 'R24', 'R', '100k', 193.04, 111.76, 'CHG_DIS', 'GND', R0402)
    two_pin(s, 'R25', 'R', '10k', 256.54, 111.76, 'TS', 'TS_SENSE', R0402)
    two_pin(s, 'C18', 'C', '100nF', 266.7, 111.76, 'TS_SENSE', 'GND', C0402)
    two_pin(s, 'R19', 'R', '1.54k 1%', 162.56, 111.76, 'ILIM', 'GND', R0402)
    two_pin(s, 'R20', 'R', '100k', 132.08, 111.76, 'VBUS', 'CHG_EN1', R0402)
    rt = s.part('RT1', 'Device:Thermistor_NTC', '10k NTC', 172.72, 111.76,
                footprint='Connector_Wire:SolderWire-0.1sqmm_1x02_P3.6mm_D0.4mm_OD1mm',
                fields={'MPN': 'NXFT15XH103FA2B (Murata leaded film NTC: same 10k/B=3380 curve '
                               'as NCP15XH103; TS thresholds assume 103AT, B=3435) - leads '
                               'soldered here, head taped to the cell (it sits beside the PCB)'})
    s.conns(rt, {'1': 'TS', '2': 'GND'})
    two_pin(s, 'C2', 'C', '10uF', 203.2, 111.76, '+BATT', 'GND', C0603,
            fields={'Voltage': '10V'})
    two_pin(s, 'C15', 'C', '10uF', 213.36, 111.76, 'VSYS', 'GND', C0603,
            fields={'Voltage': '10V'})
    two_pin(s, 'R4', 'R', '1k', 223.52, 111.76, 'VBUS', 'CHG_LED', R0402)
    d2 = s.part('D2', 'Device:LED', 'CHG (red)', 241.3, 99.06,
                footprint='LED_SMD:LED_0603_1608Metric')
    s.conns(d2, {'2': 'CHG_LED', '1': 'CHG_STAT'})

    # ---- RTC backup ---------------------------------------------------------------------
    s.text('RTC backup: cell -> MCP1700 3.0V LDO (1.6uA Iq) -> STM32 VBAT.\n'
           'A full LiPo (4.2V) minus a Schottky drop would still exceed VBAT\'s 3.6V max.\n'
           'Below ~3.2V the LDO drops out and VBAT tracks the cell (VBAT min 1.65V).',
           266.7, 30.48)
    u7 = s.part('U7', 'Regulator_Linear:MCP1700x-300xxTT', 'MCP1700T-3002E/TT', 292.1, 68.58,
                fields={'MPN': 'MCP1700T-3002E/TT'})
    s.conns(u7, {'3': '+BATT', '2': 'VBAT_RTC', '1': 'GND'})
    two_pin(s, 'C16', 'C', '1uF', 274.32, 81.28, '+BATT', 'GND', C0402)
    two_pin(s, 'C3', 'C', '1uF', 314.96, 81.28, 'VBAT_RTC', 'GND', C0402)

    # ---- Battery -----------------------------------------------------------------------
    s.text('Battery: 1-cell LiPo pouch (3.7V nominal, 4.2V full) WITH a protection board,\n'
           'JST-PH 2.0 lead. J2 pin 1 = + (Adafruit/SparkFun cells: check polarity before\n'
           'plugging in - it is not standardised across vendors). Power path is inside U1,\n'
           'so no discrete load-sharing parts are needed.',
           20.32, 129.54)
    j2 = s.part('J2', 'Connector_Generic:Conn_01x02', 'BATT (1S LiPo)', 50.8, 170.18,
                footprint='Connector_JST:JST_PH_S2B-PH-SM4-TB_1x02-1MP_P2.00mm_Horizontal')
    s.conns(j2, {'1': '+BATT', '2': 'GND'})
    s.text('Cell voltage sense for firmware (fuel estimate + graceful shutdown at ~3.4V):\n'
           '1M/1M divider -> VBAT_SENSE (4.2V -> 2.1V) to PA3 / ADC1_IN3, 100nF for the ADC\n'
           'sample. ~2uA continuous. (VBAT_RTC can no longer be used: it sits behind the 3.0V LDO.)',
           20.32, 195.58)
    two_pin(s, 'R21', 'R', '1M 1%', 81.28, 170.18, '+BATT', 'VBAT_SENSE', R0402)
    two_pin(s, 'R22', 'R', '1M 1%', 91.44, 170.18, 'VBAT_SENSE', 'GND', R0402)
    two_pin(s, 'C17', 'C', '100nF', 101.6, 170.18, 'VBAT_SENSE', 'GND', C0402)

    # ---- 3.3V buck-boost + battery undervoltage cutoff -----------------------------------
    s.text('TPS63802 buck-boost -> +3V3 (VOUT = 0.5V*(1+R7/R8) = 3.308V, datasheet Fig. 10-1).\n'
           'MODE low = power-save (PFM). Starts from VIN > 1.8V, 11uA Iq.\n'
           'UNDERVOLTAGE CUTOFF: EN has a precise threshold (1.10V rising / 1.00V falling), so\n'
           'R6/R15 (2.2M/1M) from VSYS turn the rail OFF below ~3.20V and back ON above\n'
           '~3.52V (+-3%), ~1.1uA. Backstop only: firmware shuts down gracefully first (~3.4V,\n'
           'measured via an ADC). The charger does NOT stop over-discharge; the cell\n'
           'protection board is the last line. Footprint: project lib (TI DLA0010A).',
           137.16, 129.54)
    u2 = s.part('U2', 'epaper:TPS63802', 'TPS63802DLA', 177.8, 175.26,
                fields={'MPN': 'TPS63802DLAR'})
    s.conns(u2, {'10': 'VSYS', '1': 'BB_EN', '2': 'GND', '6': '+3V3', '4': 'BB_FB',
                 '5': '3V3_PG', '9': 'BB_L1', '7': 'BB_L2', '3': 'GND', '8': 'GND'})
    two_pin(s, 'C4', 'C', '10uF', 129.54, 210.82, 'VSYS', 'GND', C0603,
            fields={'Voltage': '10V'})
    two_pin(s, 'C5', 'C', '10uF', 139.70, 210.82, 'VSYS', 'GND', C0603,
            fields={'Voltage': '10V'})
    two_pin(s, 'R6', 'R', '2.2M 1%', 149.86, 210.82, 'VSYS', 'BB_EN', R0402)
    two_pin(s, 'R15', 'R', '1M 1%', 160.02, 210.82, 'BB_EN', 'GND', R0402)
    two_pin(s, 'L1', 'L', '0.47uH', 180.34, 210.82, 'BB_L1', 'BB_L2',
            'Inductor_SMD:L_Murata_DFE201610P',
            fields={'MPN': 'DFE201612E-R47M (TI Table 10-2: 5.5A Isat; verify land pattern)'})
    two_pin(s, 'R7', 'R', '511k 1%', 190.50, 210.82, '+3V3', 'BB_FB', R0402)
    two_pin(s, 'R8', 'R', '91k 1%', 200.66, 210.82, 'BB_FB', 'GND', R0402)
    two_pin(s, 'C8', 'C', '22uF', 210.82, 210.82, '+3V3', 'GND', C0603)
    two_pin(s, 'C9', 'C', '22uF', 220.98, 210.82, '+3V3', 'GND', C0603)
    two_pin(s, 'R9', 'R', '100k', 231.14, 210.82, '+3V3', '3V3_PG', R0402)

    # ---- 5V boost for the external Waveshare HAT (v1) ------------------------------------
    s.text('TPS61023 boost -> +5V for the EXTERNAL Waveshare IT8951 HAT (v1 board: HAT on an\n'
           'SPI connector - connector lives on the peripheral sheet). VOUT = 0.6V*(1+R10/R11)\n'
           '= 4.99V. True disconnect in shutdown; R12 holds it OFF until the MCU drives EPD_5V_EN.',
           274.32, 129.54)
    u3 = s.part('U3', 'epaper:TPS61023', 'TPS61023DRL', 304.8, 175.26,
                fields={'MPN': 'TPS61023DRLR'})
    s.conns(u3, {'3': 'VSYS', '2': 'EPD_5V_EN', '6': '+5V', '1': 'BST_FB', '5': 'BST_SW',
                 '4': 'GND'})
    two_pin(s, 'C11', 'C', '10uF', 274.32, 210.82, 'VSYS', 'GND', C0603)
    two_pin(s, 'L2', 'L', '1uH', 284.48, 210.82, 'VSYS', 'BST_SW',
            'Inductor_SMD:L_Murata_DFE201610P',
            fields={'MPN': 'DFE201610P-1R0M (verify Isat vs 3.7A valley limit)'})
    two_pin(s, 'R12', 'R', '1M', 294.64, 210.82, 'EPD_5V_EN', 'GND', R0402)
    two_pin(s, 'R10', 'R', '732k 1%', 304.80, 210.82, '+5V', 'BST_FB', R0402)
    two_pin(s, 'R11', 'R', '100k 1%', 314.96, 210.82, 'BST_FB', 'GND', R0402)
    two_pin(s, 'C12', 'C', '22uF', 325.12, 210.82, '+5V', 'GND', C0805)
    two_pin(s, 'C13', 'C', '22uF', 335.28, 210.82, '+5V', 'GND', C0805)

    # ---- Reserved: always-on nanopower rail (DNP on v1) ---------------------------------
    s.text('RESERVED (DNP) for low-power v2: TPS63900 always-on\n'
           '3V3_AON (75nA Iq) for MCU + CAP1188. Replaces MAX17222,\n'
           'which is boost-only and cannot regulate a 3.65V cell down.\n'
           'VO(1) = 3.3V via CFG3 = 16.2k (SEL low); CFG1/CFG2 = 0R\n'
           '-> no input current limit. v1: R18 0R feeds 3V3_AON from\n'
           '+3V3. v2 TODO: EN needs its own UVLO (logic-level EN).',
           342.9, 30.48)
    u6 = s.part('U6', 'epaper:TPS63900', 'TPS63900DSK', 370.84, 76.2, dnp=True,
                fields={'MPN': 'TPS63900DSKR'})
    s.conns(u6, {'10': 'VSYS', '1': 'AON_EN', '2': 'GND', '6': '3V3_AON', '3': 'GND',
                 '4': 'GND', '5': 'AON_CFG3', '9': 'AON_LX1', '7': 'AON_LX2', '8': 'GND',
                 '11': 'GND'})
    two_pin(s, 'C6', 'C', '10uF', 342.9, 104.14, 'VSYS', 'GND', C0603, dnp=True)
    two_pin(s, 'R17', 'R', '100k', 353.06, 104.14, 'VSYS', 'AON_EN', R0402, dnp=True)
    two_pin(s, 'L3', 'L', '2.2uH', 363.22, 104.14, 'AON_LX1', 'AON_LX2',
            'Inductor_SMD:L_Murata_DFE201610P', dnp=True,
            fields={'MPN': '2.2uH per TPS63900 datasheet; pick the part at v2'})
    two_pin(s, 'R16', 'R', '16.2k 1%', 373.38, 104.14, 'AON_CFG3', 'GND', R0402, dnp=True)
    two_pin(s, 'C7', 'C', '22uF', 383.54, 104.14, '3V3_AON', 'GND', C0603, dnp=True)
    two_pin(s, 'R18', 'R', '0R', 393.7, 104.14, '+3V3', '3V3_AON', R0603)

    # ---- Peripheral load switch (FITTED on v1) ---------------------------------------------
    s.text('TPS22965 load switch gating 3V3_PERIPH (SDRAM, QSPI, microSD) - FITTED on v1: without\n'
           'it those parts stay powered in STANDBY (~2-20mA idle floor). ON = PERIPH_EN (PD7) with a\n'
           '100k pull-down, so the rail is OFF at reset and in STANDBY (GPIO hi-Z) automatically.\n'
           'CT 1nF (25V, per datasheet) -> ~1.3ms rise at 3.3V -> ~50mA inrush into ~21uF of load\n'
           'decoupling (no dip on +3V3). QOD: 225R discharges the rail when off. R13 = 0R bypass\n'
           '(DNP fallback). FIRMWARE: raise PERIPH_EN before FMC/QSPI/SDIO init; before dropping it,\n'
           'set those pins to analog/low so the MCU does not back-power the unpowered parts.',
           137.16, 236.22)
    u4 = s.part('U4', 'epaper:TPS22965', 'TPS22965DSG', 177.8, 264.16,
                fields={'MPN': 'TPS22965DSGR'})
    s.conns(u4, {'1': '+3V3', '4': '+3V3', '3': 'PERIPH_EN', '7': '3V3_PERIPH', '6': 'LS_CT',
                 '5': 'GND', '9': 'GND'})
    two_pin(s, 'R13', 'R', '0R', 205.74, 269.24, '+3V3', '3V3_PERIPH', R0603, dnp=True)
    two_pin(s, 'R14', 'R', '100k', 147.32, 276.86, 'PERIPH_EN', 'GND', R0402)
    two_pin(s, 'C14', 'C', '1nF', 215.9, 269.24, 'LS_CT', 'GND', C0402,
            fields={'Voltage': '25V X7R (CT pin can reach 12V)'})

    # ---- bring-up test points -------------------------------------------------------------
    s.text('Bring-up test points (one per rail).', 20.32, 228.6)
    for i, net in enumerate(['VBUS', 'VSYS', '+BATT', '+3V3', '+5V', 'GND']):
        tp = s.part('TP%d' % (1 + i), 'Connector:TestPoint', net, 30.48 + i * 15.24, 248.92,
                    footprint='TestPoint:TestPoint_Pad_D1.5mm')
        s.conns(tp, {'1': net})
    return s
