#!/usr/bin/env python3
"""Generate a 4bpp anti-aliased bitmap font (EPD_FontAA format) from a TTF/OTF.

Rasterizes each printable ASCII glyph (0x20-0x7E) at a fixed pixel size using
Pillow/FreeType, quantizes the 8-bit AA coverage down to 4 bits (matching the
IT8951 panel's 16 GC16 gray levels), and packs 2 pixels/byte with the same
nibble order used everywhere else in this project (low nibble = even x
column, high nibble = odd x column).

Each glyph is rendered proportionally (its own advance width, from the font's
real metrics) rather than forced monospace - important for a serif reading
face to look right. Height is fixed per font (ascent+descent), same approach
classic bitmap font formats (incl. the plain sFONT ones already in
Drivers/Fonts/) use.

Usage:
    python3 tools/gen_font.py --ttf <path.ttf> --size 40 --name Font40 \\
        --out-dir Drivers/Fonts [--bold]

Regenerate whenever the size/typeface choice changes - the .c output is
generated, not meant to be hand-edited.
"""
import argparse
import sys
from PIL import Image, ImageDraw, ImageFont


def quantize_to_4bit(coverage_255):
    """Map 0-255 AA coverage to a 0-15 nibble (0=no ink, 15=full ink)."""
    return (coverage_255 * 15 + 127) // 255


def render_glyph(font, ch, line_height):
    advance = int(round(font.getlength(ch)))
    if advance <= 0:
        advance = 1

    img = Image.new("L", (advance, line_height), color=0)
    draw = ImageDraw.Draw(img)
    ascent, _descent = font.getmetrics()
    draw.text((0, 0), ch, font=font, fill=255)

    pixels = img.load()
    rows = []
    for y in range(line_height):
        row = [quantize_to_4bit(pixels[x, y]) for x in range(advance)]
        rows.append(row)
    return advance, rows


def pack_rows(rows, width):
    """Pack one glyph's rows into 4bpp bytes, 2px/byte, low nibble=even x."""
    out = bytearray()
    bytes_per_row = (width + 1) // 2
    for row in rows:
        row_bytes = bytearray(bytes_per_row)
        for x, val in enumerate(row):
            byte_idx = x // 2
            if x % 2 == 0:
                row_bytes[byte_idx] |= (val & 0x0F)
            else:
                row_bytes[byte_idx] |= (val & 0x0F) << 4
        out.extend(row_bytes)
    return bytes(out)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--ttf", required=True, help="Path to source TTF/OTF")
    ap.add_argument("--size", required=True, type=int, help="Pixel size (PIL font size)")
    ap.add_argument("--name", required=True, help="C identifier, e.g. Font40")
    ap.add_argument("--out-dir", required=True, help="Output directory for <name>.c")
    args = ap.parse_args()

    font = ImageFont.truetype(args.ttf, args.size)
    ascent, descent = font.getmetrics()
    line_height = ascent + descent

    first_char = ord(' ')
    last_char = ord('~')

    glyph_blobs = []
    glyph_widths = []
    for code in range(first_char, last_char + 1):
        ch = chr(code)
        width, rows = render_glyph(font, ch, line_height)
        glyph_blobs.append(pack_rows(rows, width))
        glyph_widths.append(width)

    bitmap_name = f"{args.name}_Bitmap"
    glyphs_name = f"{args.name}_Glyphs"

    lines = []
    lines.append(f'/* Auto-generated by tools/gen_font.py - do not hand-edit.')
    lines.append(f'   Source: {args.ttf}')
    lines.append(f'   Size: {args.size}px, line height {line_height}px (ascent {ascent}, descent {descent})')
    lines.append(f'   Glyphs: 0x{first_char:02X}-0x{last_char:02X} (printable ASCII) */')
    lines.append('#include "EPD_FontAA.h"')
    lines.append('')
    lines.append(f'static const uint8_t {bitmap_name}[] = {{')

    offsets = []
    running = 0
    for blob in glyph_blobs:
        offsets.append(running)
        running += len(blob)
        hex_bytes = ", ".join(f"0x{b:02X}" for b in blob)
        lines.append(f"  {hex_bytes},")
    lines.append("};")
    lines.append("")

    lines.append(f"static const EPD_GlyphAA {glyphs_name}[] = {{")
    for i, code in enumerate(range(first_char, last_char + 1)):
        ch = chr(code)
        comment = ch.replace("\\", "\\\\").replace("'", "\\'")
        lines.append(
            f"  {{ {glyph_widths[i]}, &{bitmap_name}[{offsets[i]}] }}, /* '{comment}' */"
        )
    lines.append("};")
    lines.append("")

    lines.append(f"const EPD_FontAA {args.name} = {{")
    lines.append(f"  {glyphs_name},")
    lines.append(f"  {first_char},")
    lines.append(f"  {last_char},")
    lines.append(f"  {line_height},")
    lines.append("};")
    lines.append("")

    out_path = f"{args.out_dir}/{args.name}.c"
    with open(out_path, "w") as f:
        f.write("\n".join(lines))

    total_bytes = sum(len(b) for b in glyph_blobs)
    print(f"Wrote {out_path} ({total_bytes} bytes of glyph bitmap data, "
          f"{last_char - first_char + 1} glyphs, {line_height}px line height)")


if __name__ == "__main__":
    sys.exit(main())
